name: Dockerize - Build Test and Push

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    # give write permission so it can push container to GHCR
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # build and test JAR file using maven
      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

      # get TOKEN from secrets and login to ghcr
      # Note: TOKEN must have write:package, ropo privileges
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # inti image name of container (Amir-HShahi/bitelo)
      # then lowercase the image name : docker constraint
      # then it builds the container and pushes it ghcr
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/bitelo-api:latest" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
