name: Dockerize - Build Test and Push

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    # give write permission so it can push container to GHCR
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_DATABASE }}
        # wait for db to be healthy before running tests
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DB_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.DB_USER }}; do
            echo "Waiting for postgres..."
            sleep 3
          done

      # build and test JAR file using maven
      - name: Build and test with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ secrets.DB_DATABASE }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean verify --file pom.xml

      # get TOKEN from secrets and login to ghcr
      # Note: TOKEN must have write:package, repo privileges
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/bitelo-api:latest" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME